port: 7776
markdown: kramdown
plugins_dir:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
baseurl: /dad
sass:
  load_paths:
    - assets/_scss
    - node_modules
  style: compressed