---
upload_path: "/assets/img/gallery"
frontmatter_file_url_template: "/assets/img/gallery"
body_file_url_template: "/assets/img/gallery"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections: 
