---
pages:
- _posts/2018-05-01-home.md
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: default
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
  config:
    required: false
